import { pgTable, text, integer, jsonb, timestamp, uuid, boolean, vector } from 'drizzle-orm/pg-core';
import { users } from './users';

// NCERT Books Database
export const ncertBooks = pgTable('ncert_books', {
  id: uuid('id').primaryKey().defaultRandom(),
  class: integer('class').notNull(),
  subject: text('subject').notNull(),
  board: text('board').notNull().default('CBSE'),
  title: text('title').notNull(),
  
  // File information
  fileHash: text('file_hash').notNull(),
  fileSize: integer('file_size').notNull(),
  
  // Chapter information
  chapters: jsonb('chapters').$type<Array<{
    ch: number;
    title: string;
    url: string;
  }>>().notNull(),
  
  // Metadata
  isVirtual: boolean('is_virtual').default(false), // Auto-fetched from DIKSHA
  userId: uuid('user_id').references(() => users.id),
  
  // Timestamps
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow()
});

// NCERT Chapter Content (for auto-fetched books)
export const ncertChapters = pgTable('ncert_chapters', {
  id: uuid('id').primaryKey().defaultRandom(),
  bookId: uuid('book_id').references(() => ncertBooks.id),
  chapterNumber: integer('chapter_number').notNull(),
  title: text('title').notNull(),
  content: text('content'),
  
  // DIKSHA integration
  dikshaId: text('diksha_id'),
  dikshaUrl: text('diksha_url'),
  
  // Processing status
  isProcessed: boolean('is_processed').default(false),
  processingStatus: text('processing_status').$type<'pending' | 'processing' | 'completed' | 'failed'>().default('pending'),
  
  // Embeddings for search
  embedding: vector('embedding', { dimensions: 384 }),
  
  createdAt: timestamp('created_at').defaultNow()
});

// NCERT Flashcards (auto-generated)
export const ncertFlashcards = pgTable('ncert_flashcards', {
  id: uuid('id').primaryKey().defaultRandom(),
  bookId: uuid('book_id').references(() => ncertBooks.id),
  chapterId: uuid('chapter_id').references(() => ncertChapters.id),
  
  front: text('front').notNull(),
  back: text('back').notNull(),
  
  // Difficulty and metadata
  difficulty: integer('difficulty').$type<1 | 2 | 3 | 4 | 5>().default(3),
  topic: text('topic'),
  subtopic: text('subtopic'),
  
  // Auto-generated metadata
  isAutoGenerated: boolean('is_auto_generated').default(true),
  confidence: integer('confidence').default(85), // AI confidence score
  
  // User interaction
  userId: uuid('user_id').references(() => users.id),
  isReviewed: boolean('is_reviewed').default(false),
  reviewCount: integer('review_count').default(0),
  
  createdAt: timestamp('created_at').defaultNow()
});

// NCERT Quiz Questions (auto-generated)
export const ncertQuizQuestions = pgTable('ncert_quiz_questions', {
  id: uuid('id').primaryKey().defaultRandom(),
  bookId: uuid('book_id').references(() => ncertBooks.id),
  chapterId: uuid('chapter_id').references(() => ncertChapters.id),
  
  question: text('question').notNull(),
  options: jsonb('options').$type<string[]>().notNull(),
  correctAnswer: text('correct_answer').notNull(),
  explanation: text('explanation'),
  
  // Question metadata
  difficulty: integer('difficulty').$type<1 | 2 | 3 | 4 | 5>().default(3),
  questionType: text('question_type').$type<'mcq' | 'true_false' | 'fill_blank' | 'short_answer'>().default('mcq'),
  topic: text('topic'),
  
  // Auto-generation metadata
  isAutoGenerated: boolean('is_auto_generated').default(true),
  confidence: integer('confidence').default(80),
  
  // Usage tracking
  timesUsed: integer('times_used').default(0),
  correctRate: integer('correct_rate').default(0), // Percentage
  
  createdAt: timestamp('created_at').defaultNow()
});

// NCERT Study Plans (auto-generated)
export const ncertStudyPlans = pgTable('ncert_study_plans', {
  id: uuid('id').primaryKey().defaultRandom(),
  bookId: uuid('book_id').references(() => ncertBooks.id),
  userId: uuid('user_id').references(() => users.id),
  
  title: text('title').notNull(),
  description: text('description'),
  
  // Plan structure
  totalDays: integer('total_days').notNull(),
  currentDay: integer('current_day').default(1),
  
  // Daily schedule
  dailySchedule: jsonb('daily_schedule').$type<Array<{
    day: number;
    chapters: number[];
    topics: string[];
    estimatedTime: number; // minutes
    activities: string[];
  }>>().notNull(),
  
  // Progress tracking
  isActive: boolean('is_active').default(true),
  completedDays: integer('completed_days').default(0),
  progressPercentage: integer('progress_percentage').default(0),
  
  // Auto-generation metadata
  isAutoGenerated: boolean('is_auto_generated').default(true),
  generatedAt: timestamp('generated_at').defaultNow(),
  
  createdAt: timestamp('created_at').defaultNow()
});
