/**
 * JEE/NEET Test Suite for Accuracy Validation
 * 50+ sample problems across Physics, Chemistry, Math, Biology
 */

export interface TestProblem {
  id: string;
  subject: 'physics' | 'chemistry' | 'math' | 'biology';
  exam: 'jee' | 'neet';
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options?: string[];
  correctAnswer: string;
  solution: string;
  topic: string;
  expectedResponseType: 'explanation' | 'step-by-step' | 'concept' | 'hint';
}

export const jeeNeetProblems: TestProblem[] = [
  {
    id: 'jee-phy-1',
    subject: 'physics',
    exam: 'jee',
    difficulty: 'medium',
    question: `A particle moving in a straight line covers half the distance with speed 3 m/s. The other half of the distance is covered in two equal time intervals with speed 4.5 m/s and 7.5 m/s respectively. The average speed of the particle during this motion is:`,
    options: ['4.0 m/s', '5.0 m/s', '5.5 m/s', '4.8 m/s'],
    correctAnswer: '4.0 m/s',
    solution: `Use weighted average for non-uniform motion. For half distance at 3 m/s and half in two equal times at different speeds, calculate time-weighted average.`,
    topic: 'Kinematics',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-phy-2',
    subject: 'physics',
    exam: 'jee',
    difficulty: 'hard',
    question: `A uniform rod of length L and mass M is pivoted at the centre. Two forces F and 2F are applied on the two ends perpendicular to the rod. What is the angular acceleration?`,
    correctAnswer: '3F/(ML)',
    solution: `Torque = Iα, where I = ML²/12 for rod pivoted at center. Net torque = 2F(L/2) - F(L/2) = FL/2`,
    topic: 'Rotational Mechanics',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-phy-3',
    subject: 'physics',
    exam: 'jee',
    difficulty: 'easy',
    question: `What is the dimension of Planck's constant?`,
    options: ['ML²T⁻¹', 'ML²T⁻²', 'MLT⁻¹', 'ML²T⁻³'],
    correctAnswer: 'ML²T⁻¹',
    solution: `E = hν, so h = E/ν = (ML²T⁻²)/(T⁻¹) = ML²T⁻¹`,
    topic: 'Units and Dimensions',
    expectedResponseType: 'explanation',
  },
  {
    id: 'jee-chem-1',
    subject: 'chemistry',
    exam: 'jee',
    difficulty: 'medium',
    question: `The hybridization of carbon atoms in C-C single bond of HC≡C-CH=CH₂ is:`,
    options: ['sp-sp²', 'sp-sp³', 'sp²-sp³', 'sp³-sp³'],
    correctAnswer: 'sp-sp²',
    solution: `First carbon (triple bond) is sp, second carbon (single bond with first) is sp, third carbon (double bond) is sp²`,
    topic: 'Chemical Bonding',
    expectedResponseType: 'explanation',
  },
  {
    id: 'jee-chem-2',
    subject: 'chemistry',
    exam: 'jee',
    difficulty: 'hard',
    question: `Calculate the pH of a buffer solution containing 0.1 M CH₃COOH and 0.15 M CH₃COONa. (pKa of CH₃COOH = 4.76)`,
    correctAnswer: '4.94',
    solution: `Use Henderson-Hasselbalch equation: pH = pKa + log([salt]/[acid]) = 4.76 + log(0.15/0.1) = 4.76 + 0.18 = 4.94`,
    topic: 'Ionic Equilibrium',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-chem-3',
    subject: 'chemistry',
    exam: 'jee',
    difficulty: 'easy',
    question: `Which of the following is the strongest acid?`,
    options: ['HF', 'HCl', 'HBr', 'HI'],
    correctAnswer: 'HI',
    solution: `Acidity of hydrogen halides increases down the group due to decreasing bond strength: HI > HBr > HCl > HF`,
    topic: 'Acids and Bases',
    expectedResponseType: 'concept',
  },
  {
    id: 'jee-math-1',
    subject: 'math',
    exam: 'jee',
    difficulty: 'medium',
    question: `If f(x) = x³ - 3x² + 4, find the number of critical points in the interval [0, 3]`,
    correctAnswer: '2',
    solution: `f'(x) = 3x² - 6x = 3x(x-2). Critical points at x=0 and x=2, both in [0,3]`,
    topic: 'Differential Calculus',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-math-2',
    subject: 'math',
    exam: 'jee',
    difficulty: 'hard',
    question: `Evaluate: ∫(0 to π/2) sin²x/(sin²x + cos²x + sinx·cosx) dx`,
    correctAnswer: 'π/6',
    solution: `Use King's property: I = ∫f(x)dx = ∫f(a-x)dx. Add equations and simplify.`,
    topic: 'Integral Calculus',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-math-3',
    subject: 'math',
    exam: 'jee',
    difficulty: 'easy',
    question: `What is the value of i⁴⁷ where i = √(-1)?`,
    options: ['-i', 'i', '-1', '1'],
    correctAnswer: '-i',
    solution: `i⁴⁷ = i⁴⁴ · i³ = (i⁴)¹¹ · i³ = 1¹¹ · i³ = i³ = -i`,
    topic: 'Complex Numbers',
    expectedResponseType: 'explanation',
  },
  {
    id: 'neet-bio-1',
    subject: 'biology',
    exam: 'neet',
    difficulty: 'medium',
    question: `Which of the following is NOT a function of the Golgi apparatus?`,
    options: [
      'Formation of lysosomes',
      'Protein synthesis',
      'Glycosylation of proteins',
      'Formation of secretory vesicles'
    ],
    correctAnswer: 'Protein synthesis',
    solution: `Protein synthesis occurs in ribosomes, not Golgi apparatus. Golgi modifies, packages and transports proteins.`,
    topic: 'Cell Biology',
    expectedResponseType: 'concept',
  },
  {
    id: 'neet-bio-2',
    subject: 'biology',
    exam: 'neet',
    difficulty: 'hard',
    question: `In a Hardy-Weinberg population with two alleles A (freq p) and a (freq q), if the frequency of AA is 0.36, what is the frequency of heterozygotes?`,
    correctAnswer: '0.48',
    solution: `p² = 0.36, so p = 0.6, q = 1-p = 0.4. Heterozygote frequency = 2pq = 2(0.6)(0.4) = 0.48`,
    topic: 'Genetics',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'neet-bio-3',
    subject: 'biology',
    exam: 'neet',
    difficulty: 'easy',
    question: `Which blood vessel carries oxygenated blood from lungs to heart?`,
    options: ['Pulmonary artery', 'Pulmonary vein', 'Aorta', 'Vena cava'],
    correctAnswer: 'Pulmonary vein',
    solution: `Pulmonary vein is the only vein that carries oxygenated blood (from lungs to left atrium)`,
    topic: 'Circulation',
    expectedResponseType: 'concept',
  },
  {
    id: 'neet-phy-1',
    subject: 'physics',
    exam: 'neet',
    difficulty: 'medium',
    question: `A convex lens of focal length 20 cm forms a real image at 60 cm from the lens. What is the object distance?`,
    correctAnswer: '30 cm',
    solution: `Use lens formula: 1/f = 1/v - 1/u. 1/20 = 1/60 - 1/u, solving gives u = -30 cm`,
    topic: 'Optics',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'neet-phy-2',
    subject: 'physics',
    exam: 'neet',
    difficulty: 'easy',
    question: `The SI unit of electric field is:`,
    options: ['N/C', 'C/N', 'J/C', 'C/m'],
    correctAnswer: 'N/C',
    solution: `Electric field E = F/q, so unit is Newton/Coulomb or N/C (also V/m)`,
    topic: 'Electrostatics',
    expectedResponseType: 'explanation',
  },
  {
    id: 'neet-chem-1',
    subject: 'chemistry',
    exam: 'neet',
    difficulty: 'medium',
    question: `What is the IUPAC name of CH₃-CH(OH)-CH₂-CHO?`,
    correctAnswer: '3-hydroxybutanal',
    solution: `Principal functional group is aldehyde (-al). Number from aldehyde carbon. OH at position 3.`,
    topic: 'Nomenclature',
    expectedResponseType: 'explanation',
  },
  {
    id: 'neet-chem-2',
    subject: 'chemistry',
    exam: 'neet',
    difficulty: 'hard',
    question: `Calculate the molarity of H₂SO₄ solution if 20 mL of it neutralizes 50 mL of 0.1 M NaOH`,
    correctAnswer: '0.125 M',
    solution: `H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O. Milliequivalents: M₁V₁n₁ = M₂V₂n₂. M₁(20)(2) = 0.1(50)(1), M₁ = 0.125 M`,
    topic: 'Volumetric Analysis',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'neet-chem-3',
    subject: 'chemistry',
    exam: 'neet',
    difficulty: 'easy',
    question: `Which element has the electronic configuration [Ar] 3d¹⁰ 4s²?`,
    options: ['Cu', 'Zn', 'Ni', 'Fe'],
    correctAnswer: 'Zn',
    solution: `Zinc (Z=30) has configuration [Ar] 3d¹⁰ 4s². Note: Cu is [Ar] 3d¹⁰ 4s¹`,
    topic: 'Atomic Structure',
    expectedResponseType: 'concept',
  },
  // Additional JEE Physics Problems
  {
    id: 'jee-phy-4',
    subject: 'physics',
    exam: 'jee',
    difficulty: 'medium',
    question: `A block of mass 2 kg is pushed against a spring of spring constant 400 N/m, compressing it by 0.1 m. Find the maximum speed of the block when released.`,
    correctAnswer: '2 m/s',
    solution: `Energy conservation: (1/2)kx² = (1/2)mv². (1/2)(400)(0.1)² = (1/2)(2)v². v = 2 m/s`,
    topic: 'Work Energy Power',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-phy-5',
    subject: 'physics',
    exam: 'jee',
    difficulty: 'hard',
    question: `A wire of resistance R is stretched to double its length. What is its new resistance?`,
    correctAnswer: '4R',
    solution: `R = ρL/A. When length doubles, area becomes A/2 (volume constant). New R = ρ(2L)/(A/2) = 4ρL/A = 4R`,
    topic: 'Current Electricity',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-phy-6',
    subject: 'physics',
    exam: 'jee',
    difficulty: 'easy',
    question: `In which process is work done by the gas maximum for the same change in volume?`,
    options: ['Isothermal', 'Adiabatic', 'Isobaric', 'Isochoric'],
    correctAnswer: 'Isobaric',
    solution: `Work = ∫PdV. For same ΔV, isobaric has highest constant pressure throughout, hence maximum work.`,
    topic: 'Thermodynamics',
    expectedResponseType: 'explanation',
  },
  // Additional JEE Chemistry Problems
  {
    id: 'jee-chem-4',
    subject: 'chemistry',
    exam: 'jee',
    difficulty: 'medium',
    question: `Among the following, the compound that is both paramagnetic and coloured is:`,
    options: ['K₂Cr₂O₇', 'K₃[Fe(CN)₆]', '[Ni(CO)₄]', 'TiCl₄'],
    correctAnswer: 'K₃[Fe(CN)₆]',
    solution: `Fe³⁺ in K₃[Fe(CN)₆] has unpaired electrons (paramagnetic) and shows d-d transitions (colored)`,
    topic: 'Coordination Chemistry',
    expectedResponseType: 'explanation',
  },
  {
    id: 'jee-chem-5',
    subject: 'chemistry',
    exam: 'jee',
    difficulty: 'hard',
    question: `The standard reduction potential for Cu²⁺/Cu is +0.34V. Calculate E for 0.1M Cu²⁺ solution at 25°C.`,
    correctAnswer: '0.31 V',
    solution: `Nernst equation: E = E° - (0.059/n)log(1/[Cu²⁺]). E = 0.34 - (0.059/2)log(10) = 0.34 - 0.03 = 0.31V`,
    topic: 'Electrochemistry',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-chem-6',
    subject: 'chemistry',
    exam: 'jee',
    difficulty: 'easy',
    question: `Which one is the strongest Bronsted base?`,
    options: ['ClO⁻', 'ClO₂⁻', 'ClO₃⁻', 'ClO₄⁻'],
    correctAnswer: 'ClO⁻',
    solution: `Weaker the acid, stronger its conjugate base. HClO is weakest acid, so ClO⁻ is strongest base.`,
    topic: 'Acids and Bases',
    expectedResponseType: 'concept',
  },
  // Additional JEE Math Problems
  {
    id: 'jee-math-4',
    subject: 'math',
    exam: 'jee',
    difficulty: 'medium',
    question: `If the sum of n terms of an AP is 3n² + 5n, find the 10th term.`,
    correctAnswer: '62',
    solution: `Sn = 3n² + 5n. S₁₀ = 3(100) + 50 = 350, S₉ = 3(81) + 45 = 288. a₁₀ = S₁₀ - S₉ = 62`,
    topic: 'Sequences and Series',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-math-5',
    subject: 'math',
    exam: 'jee',
    difficulty: 'hard',
    question: `Find the area enclosed by |x| + |y| = 1`,
    correctAnswer: '2 square units',
    solution: `This forms a square with vertices at (1,0), (0,1), (-1,0), (0,-1). Diagonal = 2, Area = (1/2)×2×2 = 2`,
    topic: 'Coordinate Geometry',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-math-6',
    subject: 'math',
    exam: 'jee',
    difficulty: 'easy',
    question: `The probability that a leap year has 53 Sundays is:`,
    options: ['1/7', '2/7', '3/7', '4/7'],
    correctAnswer: '2/7',
    solution: `Leap year has 366 days = 52 weeks + 2 days. These 2 days can be (Sun,Mon) or (Mon,Tue)...(Sat,Sun). P(53 Sundays) = 2/7`,
    topic: 'Probability',
    expectedResponseType: 'explanation',
  },
  // Additional NEET Biology Problems
  {
    id: 'neet-bio-4',
    subject: 'biology',
    exam: 'neet',
    difficulty: 'medium',
    question: `In C4 plants, the primary CO₂ acceptor is:`,
    options: ['RuBP (5C)', 'PEP (3C)', 'PGA (3C)', 'OAA (4C)'],
    correctAnswer: 'PEP (3C)',
    solution: `In C4 plants, CO₂ is first fixed by PEP carboxylase using PEP (3C) to form OAA (4C)`,
    topic: 'Photosynthesis',
    expectedResponseType: 'concept',
  },
  {
    id: 'neet-bio-5',
    subject: 'biology',
    exam: 'neet',
    difficulty: 'hard',
    question: `If a colour blind man marries a normal woman whose father was colour blind, what percentage of sons will be colour blind?`,
    correctAnswer: '50%',
    solution: `Man: XcY, Woman: XCXc (carrier). Sons: XCY (50%) normal, XcY (50%) color blind`,
    topic: 'Genetics',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'neet-bio-6',
    subject: 'biology',
    exam: 'neet',
    difficulty: 'easy',
    question: `Which hormone is called emergency hormone?`,
    options: ['Insulin', 'Adrenaline', 'Thyroxine', 'Testosterone'],
    correctAnswer: 'Adrenaline',
    solution: `Adrenaline is released during stress/emergency, increases heart rate, blood pressure for fight or flight response`,
    topic: 'Endocrinology',
    expectedResponseType: 'concept',
  },
  // Additional NEET Physics Problems
  {
    id: 'neet-phy-3',
    subject: 'physics',
    exam: 'neet',
    difficulty: 'medium',
    question: `A galvanometer of resistance 50Ω gives full scale deflection for 5mA current. To convert it to ammeter of range 0-5A, the shunt resistance required is:`,
    correctAnswer: '0.05 Ω',
    solution: `Ig = 5mA, G = 50Ω, I = 5A. Shunt S = IgG/(I-Ig) = (0.005)(50)/(5-0.005) ≈ 0.05Ω`,
    topic: 'Current Electricity',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'neet-phy-4',
    subject: 'physics',
    exam: 'neet',
    difficulty: 'easy',
    question: `The coefficient of linear expansion of brass is 2×10⁻⁵/°C. If the radius of a brass sphere is 10 cm, the increase in radius when heated from 20°C to 120°C is:`,
    correctAnswer: '0.02 cm',
    solution: `Δr = r×α×ΔT = 10×(2×10⁻⁵)×100 = 0.02 cm`,
    topic: 'Thermal Expansion',
    expectedResponseType: 'step-by-step',
  },
  // Additional NEET Chemistry Problems
  {
    id: 'neet-chem-4',
    subject: 'chemistry',
    exam: 'neet',
    difficulty: 'medium',
    question: `The half-life of a radioactive isotope is 3 hours. After 18 hours, what fraction remains?`,
    correctAnswer: '1/64',
    solution: `n = t/t₁/₂ = 18/3 = 6 half-lives. Remaining fraction = (1/2)⁶ = 1/64`,
    topic: 'Nuclear Chemistry',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'neet-chem-5',
    subject: 'chemistry',
    exam: 'neet',
    difficulty: 'easy',
    question: `Which vitamin is water soluble?`,
    options: ['Vitamin A', 'Vitamin D', 'Vitamin C', 'Vitamin K'],
    correctAnswer: 'Vitamin C',
    solution: `Vitamin C (ascorbic acid) is water soluble. A, D, E, K are fat soluble vitamins`,
    topic: 'Biomolecules',
    expectedResponseType: 'concept',
  },
  // More JEE Advanced Level Problems
  {
    id: 'jee-phy-7',
    subject: 'physics',
    exam: 'jee',
    difficulty: 'hard',
    question: `A particle is moving in a circle of radius R with constant speed v. The magnitude of average acceleration when it completes half circle is:`,
    correctAnswer: '2v²/(πR)',
    solution: `Change in velocity = 2v (opposite directions). Time = πR/v. Average acceleration = 2v/(πR/v) = 2v²/(πR)`,
    topic: 'Circular Motion',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-chem-7',
    subject: 'chemistry',
    exam: 'jee',
    difficulty: 'hard',
    question: `For the reaction A → B, rate constant k = 4.5×10⁻⁵ sec⁻¹. What percentage of A will remain after 10 hours?`,
    correctAnswer: '8.8%',
    solution: `First order: ln([A]₀/[A]) = kt. t=36000s. ln([A]₀/[A]) = 4.5×10⁻⁵×36000 = 1.62. [A]/[A]₀ = e⁻¹·⁶² = 0.088 = 8.8%`,
    topic: 'Chemical Kinetics',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-math-7',
    subject: 'math',
    exam: 'jee',
    difficulty: 'hard',
    question: `Find the equation of tangent to ellipse x²/4 + y²/3 = 1 at point (√3, 3/2)`,
    correctAnswer: 'x√3/4 + y/2 = 1',
    solution: `Tangent to x²/a² + y²/b² = 1 at (x₁,y₁) is xx₁/a² + yy₁/b² = 1. Here: x(√3)/4 + y(3/2)/3 = 1`,
    topic: 'Conic Sections',
    expectedResponseType: 'step-by-step',
  },
  // More NEET Problems
  {
    id: 'neet-bio-7',
    subject: 'biology',
    exam: 'neet',
    difficulty: 'medium',
    question: `The number of ATPs produced in glycolysis is:`,
    options: ['2 net ATP', '4 net ATP', '8 net ATP', '38 net ATP'],
    correctAnswer: '2 net ATP',
    solution: `Glycolysis produces 4 ATP but uses 2 ATP in initial steps. Net gain = 4 - 2 = 2 ATP`,
    topic: 'Respiration',
    expectedResponseType: 'explanation',
  },
  {
    id: 'neet-bio-8',
    subject: 'biology',
    exam: 'neet',
    difficulty: 'hard',
    question: `A DNA strand has 20% thymine. What percentage of cytosine will it have?`,
    correctAnswer: '30%',
    solution: `T=20%, so A=20% (Chargaff). Remaining = 100-40 = 60%. G+C = 60%, so C = 30%`,
    topic: 'Molecular Biology',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'neet-phy-5',
    subject: 'physics',
    exam: 'neet',
    difficulty: 'medium',
    question: `Two resistances 4Ω and 6Ω are connected in parallel. The equivalent resistance is:`,
    correctAnswer: '2.4 Ω',
    solution: `1/Req = 1/4 + 1/6 = (3+2)/12 = 5/12. Req = 12/5 = 2.4Ω`,
    topic: 'Electricity',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'neet-chem-6',
    subject: 'chemistry',
    exam: 'neet',
    difficulty: 'medium',
    question: `The shape of SF₆ molecule is:`,
    options: ['Tetrahedral', 'Square planar', 'Octahedral', 'Trigonal bipyramidal'],
    correctAnswer: 'Octahedral',
    solution: `SF₆: S has 6 bond pairs, 0 lone pairs. Hybridization = sp³d². Geometry = Octahedral`,
    topic: 'VSEPR Theory',
    expectedResponseType: 'explanation',
  },
  // Additional varied difficulty problems
  {
    id: 'jee-phy-8',
    subject: 'physics',
    exam: 'jee',
    difficulty: 'medium',
    question: `A body is thrown vertically upward with velocity 20 m/s. Find maximum height (g=10 m/s²)`,
    correctAnswer: '20 m',
    solution: `v² = u² - 2gh. At max height v=0. 0 = 400 - 2(10)h. h = 20m`,
    topic: 'Kinematics',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-chem-8',
    subject: 'chemistry',
    exam: 'jee',
    difficulty: 'medium',
    question: `The orbital angular momentum of electron in 3d orbital is:`,
    correctAnswer: '√6 ℏ',
    solution: `L = √(l(l+1))ℏ. For d orbital, l=2. L = √(2×3)ℏ = √6 ℏ`,
    topic: 'Quantum Numbers',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'jee-math-8',
    subject: 'math',
    exam: 'jee',
    difficulty: 'medium',
    question: `If tan⁻¹(1) + tan⁻¹(2) + tan⁻¹(3) = π, find the value of tan⁻¹(1) + tan⁻¹(1/2) + tan⁻¹(1/3)`,
    correctAnswer: 'π/2',
    solution: `Let a = tan⁻¹(1/2), b = tan⁻¹(1/3). tan⁻¹(1) = π/4. Since tan⁻¹(x) + tan⁻¹(1/x) = π/2, answer = π/2`,
    topic: 'Inverse Trigonometry',
    expectedResponseType: 'step-by-step',
  },
  {
    id: 'neet-bio-9',
    subject: 'biology',
    exam: 'neet',
    difficulty: 'easy',
    question: `The powerhouse of the cell is:`,
    options: ['Ribosome', 'Mitochondria', 'Golgi body', 'Nucleus'],
    correctAnswer: 'Mitochondria',
    solution: `Mitochondria produces ATP through cellular respiration, hence called powerhouse of cell`,
    topic: 'Cell Biology',
    expectedResponseType: 'concept',
  },
  {
    id: 'neet-bio-10',
    subject: 'biology',
    exam: 'neet',
    difficulty: 'medium',
    question: `The enzyme that catalyzes peptide bond formation is:`,
    options: ['DNA polymerase', 'RNA polymerase', 'Peptidyl transferase', 'Helicase'],
    correctAnswer: 'Peptidyl transferase',
    solution: `Peptidyl transferase is a ribozyme (23S rRNA) that catalyzes peptide bond formation during translation`,
    topic: 'Protein Synthesis',
    expectedResponseType: 'concept',
  },
  {
    id: 'neet-phy-6',
    subject: 'physics',
    exam: 'neet',
    difficulty: 'easy',
    question: `1 horse power (HP) is equal to:`,
    options: ['746 W', '1000 W', '500 W', '100 W'],
    correctAnswer: '746 W',
    solution: `1 HP = 746 Watts (standard conversion)`,
    topic: 'Units and Dimensions',
    expectedResponseType: 'concept',
  },
  {
    id: 'neet-chem-7',
    subject: 'chemistry',
    exam: 'neet',
    difficulty: 'easy',
    question: `The common name of sodium carbonate decahydrate is:`,
    options: ['Baking soda', 'Washing soda', 'Caustic soda', 'Soda ash'],
    correctAnswer: 'Washing soda',
    solution: `Na₂CO₃·10H₂O is washing soda. Baking soda is NaHCO₃`,
    topic: 'Inorganic Chemistry',
    expectedResponseType: 'concept',
  },
  // Final set to reach 50+
  {
    id: 'jee-phy-9',
    subject: 'physics',
    exam: 'jee',
    difficulty: 'easy',
    question: `Escape velocity on Earth's surface is approximately:`,
    options: ['7.9 km/s', '11.2 km/s', '15 km/s', '20 km/s'],
    correctAnswer: '11.2 km/s',
    solution: `Escape velocity = √(2GM/R) ≈ 11.2 km/s for Earth`,
    topic: 'Gravitation',
    expectedResponseType: 'concept',
  },
  {
    id: 'jee-chem-9',
    subject: 'chemistry',
    exam: 'jee',
    difficulty: 'easy',
    question: `The shape of NH₃ molecule is:`,
    options: ['Tetrahedral', 'Trigonal planar', 'Trigonal pyramidal', 'Linear'],
    correctAnswer: 'Trigonal pyramidal',
    solution: `NH₃ has 3 bond pairs and 1 lone pair on N. Shape is trigonal pyramidal (not tetrahedral)`,
    topic: 'Chemical Bonding',
    expectedResponseType: 'concept',
  },
  {
    id: 'jee-math-9',
    subject: 'math',
    exam: 'jee',
    difficulty: 'easy',
    question: `The value of log₂(16) is:`,
    options: ['2', '3', '4', '5'],
    correctAnswer: '4',
    solution: `log₂(16) = log₂(2⁴) = 4`,
    topic: 'Logarithms',
    expectedResponseType: 'explanation',
  },
  {
    id: 'neet-bio-11',
    subject: 'biology',
    exam: 'neet',
    difficulty: 'easy',
    question: `The functional unit of kidney is:`,
    options: ['Neuron', 'Nephron', 'Alveoli', 'Villi'],
    correctAnswer: 'Nephron',
    solution: `Nephron is the functional and structural unit of kidney that filters blood and forms urine`,
    topic: 'Excretory System',
    expectedResponseType: 'concept',
  },
  {
    id: 'neet-phy-7',
    subject: 'physics',
    exam: 'neet',
    difficulty: 'easy',
    question: `Myopia can be corrected by using:`,
    options: ['Convex lens', 'Concave lens', 'Cylindrical lens', 'Bifocal lens'],
    correctAnswer: 'Concave lens',
    solution: `Myopia (short-sightedness) is corrected using concave (diverging) lens`,
    topic: 'Optics',
    expectedResponseType: 'concept',
  },
  {
    id: 'neet-chem-8',
    subject: 'chemistry',
    exam: 'neet',
    difficulty: 'easy',
    question: `The pH of pure water at 25°C is:`,
    options: ['0', '7', '14', '1'],
    correctAnswer: '7',
    solution: `Pure water is neutral with pH = 7 at 25°C ([H⁺] = [OH⁻] = 10⁻⁷M)`,
    topic: 'Ionic Equilibrium',
    expectedResponseType: 'concept',
  },
];

export function getTestProblems(filters: {
  subject?: string;
  exam?: string;
  difficulty?: string;
  limit?: number;
}): TestProblem[] {
  let filtered = [...jeeNeetProblems];
  
  if (filters.subject) {
    filtered = filtered.filter(p => p.subject === filters.subject);
  }
  
  if (filters.exam) {
    filtered = filtered.filter(p => p.exam === filters.exam);
  }
  
  if (filters.difficulty) {
    filtered = filtered.filter(p => p.difficulty === filters.difficulty);
  }
  
  if (filters.limit) {
    filtered = filtered.slice(0, filters.limit);
  }
  
  return filtered;
}

export function getRandomProblems(count: number = 10): TestProblem[] {
  const shuffled = [...jeeNeetProblems].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
